root: ./docs

structure:
  readme: README.md
  summary: SUMMARY.md

format: website

title: HRMS API Documentation
description: Comprehensive API documentation for Human Resource Management System

github:
  edit: true
  issues: true

plugins:
  - search
  - hints
  - code-blocks
  - api-reference

navigation:
  title: HRMS API
  logo: assets/logo.png

appearance:
  theme: light
  primaryColor: "#3B82F6"
  accentColor: "#10B981"

pdf:
  fontSize: 12
  paperSize: a4
  margin:
    right: 62
    left: 62
    top: 56
    bottom: 56
  headerTemplate: "<p style='text-align:center; font-size:10px;'><span class='title'></span></p>"
  footerTemplate: "<p style='text-align:center; font-size:10px;'><span class='pageNumber'></span></p>"
